### PR TITLE
do not skip subs without line_items for csv download

### PR DESCRIPTION
**Pull request by peterberkenbosch**

### CODE REVIEW

**Comment by fastjames** [comment]
Does this have a card associated with it? A subscription with no line items sounds like an invalid data state to me, so I want to know more about what generated this fix.

**Comment by peterberkenbosch** [comment]
Yes there is: https://app.clubhouse.io/enginecommerce/story/3604/user-can-export-subscriptions-csv-that-has-data-matching-the-stats-shown-on-the-subscriptions-landing-page 

I do agree though, I focused on getting the export matching the total active subscription count. However, it might be better to fix the total active subscription count.

**Comment by fastjames** [comment]
Yes, I think you have uncovered a new question: what are these active subscriptions doing with no line items? That seems like a question for a separate card that @LukeSettle can investigate, since he is working in that area right now.

**Comment by fastjames** [comment]
Adding @LukeSettle as a reviewer so this comes to his attention.

**Comment by fastjames** [comment]
@peterberkenbosch @LukeSettle noted that while these subscriptions may not have a line_item association, they may still have a `subscribable` association. Would that be usable in place of the line item's variant?

**Review by LukeSettle — APPROVED** [review]
Currently, this will only leave out one subscription which was from the import and hasn't yet processed. Once it does I will update the line item and we shouldn't have any issues with this again so I'd say this is good to go :cake:

**Comment by fastjames** [comment]
Despite the PR title, after reading over this it seems that it _does_ skip subscriptions which are missing the line item association. I am fine with that, as I think we all understand what's going on now with the data.

**Review by fastjames — APPROVED** [review]

**Comment by fastjames** [comment]
Squashed and merged.

**Pull request closed without merging**
