### PR TITLE
fixed minor style/layout issues with subscriptions

### PR DESCRIPTION
**Pull request by cnorm35**
https://trello.com/c/fUomDhvL/116-admin-should-be-able-to-create-a-new-subscription-when-subscriptions-are-present

minor tweaks to style and layout for items found during QA

### CODE REVIEW

**Comment by cnorm35** [comment]
[Admin should be able to create a new subscription when subscriptions are present](https://trello.com/c/fUomDhvL/116-admin-should-be-able-to-create-a-new-subscription-when-subscriptions-are-present)

**Review by jacobherrington — APPROVED** [review]

**Comment by jacobherrington** [comment]
Interesting to note that this markup is using classes from skeleton css.

**Comment by cnorm35** [comment]
THANK YOU!  i was trying to figure out where those classes were from, and couldn't figure it out

**Comment by jacobeubanks** [comment]
Looks good! I think the card is referring to the absence of the 'new subscription' button in the header, just like the new order button here, which that would be engine_storefront_backend_ui feature:
screen shot 2018-09-18 at 1 29 12 pm

**Comment by jacobeubanks** [comment]
@cnorm35 Yes, here you go, the fun of skeleton.scss from 2011: https://github.com/solidusio/solidus/blob/master/frontend/app/assets/stylesheets/spree/frontend/_skeleton.scss

**Review by jacobeubanks — APPROVED** [review]

**Comment by cnorm35** [comment]
thanks for that clarification @jacobeubanks, was doing some QA related items and fixed up a few things.  i'll make that update to the backend_ui repo now

**Comment by cnorm35** [comment]
@jacobherrington @jacobeubanks could you gents re-review the changes adding the 'New Subscription' button

**Comment by fastjames** [comment]
Are these markup changes specific to engine? If so, then we are hard-forking from the upstream repo by merging this.

**Comment by fastjames** [comment]
What we have done previously is to make engine-specific changes in `engine_storefront_backend_ui`.

**Comment by cnorm35** [comment]
that makes sense, i was thinking keeping all the subscription changes in the subscription repo, but i'd rather move all those to the backend_ui to keep us in-sync with the forked repo

**Comment by cnorm35** [comment]
closing in favor of changes in https://github.com/geminimvp/engine_storefront_backend_ui/pull/155

**Pull request closed without merging**
