### PR TITLE
Feature/subscription quick stats

### PR DESCRIPTION
**Pull request by LukeSettle**
Adds quick stats to the subscription index. View file is found here: https://github.com/geminimvp/engine_storefront_backend_ui/pull/178

image

### CODE REVIEW

**Review by cnorm35 — APPROVED** [review]

**Comment by fastjames** [comment]
@LukeSettle I tried the failing specs locally, and after doing a `git rebase gemini_master` they passed for me.

**Comment by LukeSettle** [comment]
@fastjames they seem to be failing intermittently. I'll try with the rebase.

**Comment by LukeSettle** [comment]
Tests are passing locally. Trying to figure out what's up with CI...

**Comment by LukeSettle** [comment]
They still seem a  little flakey... but it passed 🎊

**Review by fastjames — APPROVED** [review]
Looks good. :cake:

**Pull request merged**
